### ISSUE TITLE
`https://js.adapools.org/groups.json` is returning an empty array 

### ISSUE THREAD

**Issue by andreAmorimF** [cardano-community/pool_groups#20]
**Describe the bug**
`https://js.adapools.org/groups.json` is returning an empty array (probably since their migration to cexplorer), creating more discrepancies with the `adastat` results. Maybe we shouldn't rely on this API anymore (at first glance, there is no correspondent endpoint on cexplorer).

**To Reproduce**
1. GET request on `https://js.adapools.org/groups.json`

**Comment by rdlrt** [comment]
It currently already gets skipped as a source, will be replaced by Koios as source soon
