### ISSUE TITLE
One entry in singlepooloperators.json refers to 1PCT pool

### ISSUE THREAD

**Issue by katomm** [cardano-community/pool_groups#21]
Hello,
I highly appreciate this project and want to thank everyone involved. I stumbled across this one reference in [singlepooloperators.json](https://github.com/cardano-community/pool_groups/blob/main/singlepooloperators.json) to 1PCT pools. Does anyone know if this operator is making fun of 1PCT, or maybe leverage the 1PCT brand, or is this pool even part of the 1PCT pool cluster?

```
"c0c231446dc398936f0f85506072f10641b861ce5012c0fcb1051442": {
    "name": "1PCT Pools at 1-PCT.com",
    "ticker": "WOW"
  },
```

**Comment by rdlrt** [comment]
Not part of 1PCT cluster, seems to be someone trying to leverage success from 1PCT using names targetting unsuspecting delegators 👿

**Comment by katomm** [comment]
🙏 thank you
