### ISSUE TITLE
Cpoolsunited is a collaboration of small stake pool operators, not a multi pool operation

### ISSUE THREAD

**Issue by filip-strelec** [cardano-community/pool_groups#26]
https://www.cpoolsunited.com/ 
consists of several small stake pool operators that share some of the relays in order to curb the high price of the operation while doing minimal blocks.

The collaboration uses CPU profits to pay for the shared relays, the rest we are donating, so it's a non-profit pool

Shouldn't the pools in collaboration be listed as single pool operators?

**Comment by filip-strelec** [comment]
here's a ticket for the issue, initially opened in eternl browser support discord
![image](https://github.com/cardano-community/pool_groups/assets/38225333/3663ba3f-e62e-4af5-8ac9-83abc97b7ae0)

**Comment by dmitrystas** [comment]
> Shouldn't the pools in collaboration be listed as single pool operators?

Since the relay is a single point of failure for all operators who use it, imo no, they shouldn't.

**Comment by filip-strelec** [comment]
> Since the relay is a single point of failure for all operators who use it, imo no, they shouldn't.

some of us have custom relays, alongside shared relays, so that removes the "single point of failure"

Also this is hurting us, most people want single pool operators, now you are punishing small pools that would be dead months/years ago, if it weren't for relay sharing and colaboration.

There's also some multi pool operations that use different relays, from my understanding, we do not give information about multi pools so the user knows there's a single point of faulure, but that to inform the user that this user made multiple pools..

**Comment by rdlrt** [comment]
![Screenshot_20230826-233043_1](https://github.com/cardano-community/pool_groups/assets/3169068/7fb16210-d150-4738-b4d8-f42352ca723c)

The rules for listing are clearly listed in the REaDME of the repo. Folks are free to add each other to relay via topology, if they end up registering pools with same relay - they would naturally end up with other pool clusters.

> There's also some multi pool operations that use different relays, from my understanding, we do not give information about multi pools 

Feel free to report any clusters missing (it's not purely based on relays, but also branding/owners/splitting/etc. The list is only as strong as community who reports missing cluster definitions.

**Comment by filip-strelec** [comment]
> folks are free to add each other to relay via topology
That doesn't fix the problem if the relay they use goes dark, best way is to have multiple relays registered and each connected to different topology, isn't it?

I understand what you are trying to explain, cpoolsunited was envisioned to help the small pool operation with relay, knowledge etc. sharing, but now IMO, it's hurting pool operators because the people think there's only one owner for all these pools.

Is there any possibility that we get the status of single pool operators? The pool i run, has bare metal relay, alongside collaboration relays, would that qualify it to go to single pool stack?
 
 Wallets like eternl use this data, and this way, the end user gets the wrong information, based on that, he/she will make his/her decisions accordingly.
 
 Either way, thank you for the information

**Comment by rdlrt** [comment]
Sorry, but the whole point of this repo is to simplify and not get into perceptions, I think adding special cases where folks share relays or branding/alliances-marketed-together will not only complicate flows, but also start into word-play negotiations, etc. If you want to split pools to be single pool operators, the considerations are as per README in root of the repo. Apologies if this is not as per your preference/perceptions , but hope you can see the background behind reasoning 🙏🏻

**Comment by filip-strelec** [comment]
Although I don't necessarily agree fully, I understand completely.
The idea was to help small pool operators, but now, we are harming them, because they are labeled as multi-pool owners...

It is what it is, Thank you for taking your time and giving a detailed explanation :)

**Comment by filip-strelec** [comment]
> Since the relay is a single point of failure for all operators who use it, imo no, they shouldn't.

@rdlrt  could you, at least put my pool as a single pool operator, considering I do not share all the relays with the team, I have my own, 1 bare metal relay that's registered only to my pool.

Pool is |VENUS| Fresco pool

And i will tell the team, if they want to get the status of single pool operator, that they need to have at least 1 independent relay
