### ISSUE TITLE
EDEN pool is not in a pool group

### ISSUE THREAD

**Issue by PegasusPool** [cardano-community/pool_groups#7]
EDEN pool is under the solo groups:

{
      "pool_hash": "d5b90a198d2411b5c82fbdfee5f94b86de49a8589bfa7720b9de358f",
      "ticker": "EDEN",
      "name": "Garden Pool"
},

However there are Garden Pool Two and Garden Pool Three pools with the same EDEN ticker run by the same operator.

**Comment by rdlrt** [comment]
Closed in #11
